# M4_High-model

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt 

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
data =pd.read_csv("Crypto_data2.csv")

In [4]:
data

Unnamed: 0        Date         Open         High          Low  \
0               0  2014-12-09   361.894989   363.066986   344.950989   
1               1  2014-12-10   352.204987   352.384003   346.364990   
2               2  2014-12-11   344.339996   361.356995   338.763000   
3               3  2014-12-12   350.833008   352.983002   349.290985   
4               4  2014-12-13   352.381012   352.381012   346.588013   
...           ...         ...          ...          ...          ...   
10129        1570  2022-03-09  1754.225098  1918.758301  1747.854126   
10130        1571  2022-03-10  1912.570557  1914.414185  1765.506348   
10131        1572  2022-03-11  1773.831665  1793.170654  1709.868164   
10132        1573  2022-03-12  1750.544189  1788.684692  1744.583252   
10133        1574  2022-03-13  1739.929932  1780.157715  1695.159424   

             Close    Adj Close    Volume Crypto  
0       352.218994   352.218994  32915500    BTC  
1       346.364990   346.364990  16427700    BTC  
2       350.506012   350.506012  32431300    BTC  
3       352.541992   352.541992  16989800    BTC  
4       347.376007   347.376007  11675900    BTC  
...            ...          ...       ...    ...  
10129  1913.793213  1913.793213  65771052    MKR  
10130  1773.745972  1773.745972  62791406    MKR  
10131  1750.467651  1750.467651  56816724    MKR  
10132  1744.610962  1744.610962  36075999    MKR  
10133  1727.445068  1727.445068  40633560    MKR  

[10134 rows x 9 columns]

In [5]:
data.isnull().any()

Unnamed: 0    False
Date          False
Open          False
High          False
Low           False
Close         False
Adj Close     False
Volume        False
Crypto        False
dtype: bool

In [6]:
data.isnull().sum()

Unnamed: 0    0
Date          0
Open          0
High          0
Low           0
Close         0
Adj Close     0
Volume        0
Crypto        0
dtype: int64

In [7]:
data.dropna(inplace =True)

In [8]:
data.isnull().sum()

Unnamed: 0    0
Date          0
Open          0
High          0
Low           0
Close         0
Adj Close     0
Volume        0
Crypto        0
dtype: int64

In [9]:
data.columns

Index(['Unnamed: 0', 'Date', 'Open', 'High', 'Low', 'Close', 'Adj Close',
       'Volume', 'Crypto'],
      dtype='object')

In [10]:
data.drop(['Unnamed: 0', 'Adj Close','Volume' ],axis =1, inplace =True)
data

Date         Open         High          Low        Close Crypto
0      2014-12-09   361.894989   363.066986   344.950989   352.218994    BTC
1      2014-12-10   352.204987   352.384003   346.364990   346.364990    BTC
2      2014-12-11   344.339996   361.356995   338.763000   350.506012    BTC
3      2014-12-12   350.833008   352.983002   349.290985   352.541992    BTC
4      2014-12-13   352.381012   352.381012   346.588013   347.376007    BTC
...           ...          ...          ...          ...          ...    ...
10129  2022-03-09  1754.225098  1918.758301  1747.854126  1913.793213    MKR
10130  2022-03-10  1912.570557  1914.414185  1765.506348  1773.745972    MKR
10131  2022-03-11  1773.831665  1793.170654  1709.868164  1750.467651    MKR
10132  2022-03-12  1750.544189  1788.684692  1744.583252  1744.610962    MKR
10133  2022-03-13  1739.929932  1780.157715  1695.159424  1727.445068    MKR

[10134 rows x 6 columns]

# Make  target value in USD

In [11]:
#data["Today_USD"] =  (data["Open"] + data["Close"] ) /2
data["Today_USD"] =  (data["High"])


In [12]:
data["Crypto"].unique()

array(['BTC', 'LTC', 'BNB', 'ETH', 'MKR'], dtype=object)

In [13]:
# making tomorrow result 
for id, crip in enumerate(data["Crypto"].unique()):
    ind_cript = data[data["Crypto"] == crip]
    ind_cript["Tomorrow_price(USD)"] =ind_cript["Today_USD"].shift(-1) 
    ind_cript.head()
    ind_cript.dropna(inplace =True)
    if (id ==0 ):
        BTC =ind_cript
    elif (id ==1 ):
        ADA = ind_cript
    elif (id == 2 ):
        BNB = ind_cript
    elif (id == 3 ):
        ETH = ind_cript
    elif (id == 4 ):
        USDT = ind_cript
        

file = pd.concat([BTC,ETH, BNB, ADA, USDT])
#files = pd.concat([BTC,ETH, BNB])

In [14]:
file.tail()

Date         Open         High          Low        Close Crypto  \
10128  2022-03-08  1745.794800  1790.965698  1722.096802  1754.612671    MKR   
10129  2022-03-09  1754.225098  1918.758301  1747.854126  1913.793213    MKR   
10130  2022-03-10  1912.570557  1914.414185  1765.506348  1773.745972    MKR   
10131  2022-03-11  1773.831665  1793.170654  1709.868164  1750.467651    MKR   
10132  2022-03-12  1750.544189  1788.684692  1744.583252  1744.610962    MKR   

         Today_USD  Tomorrow_price(USD)  
10128  1790.965698          1918.758301  
10129  1918.758301          1914.414185  
10130  1914.414185          1793.170654  
10131  1793.170654          1788.684692  
10132  1788.684692          1780.157715

In [15]:
for x, y in enumerate(data["Crypto"].unique()):
    file["Crypto"] = file["Crypto"].replace({y:  x})
    print("The Crypto ", y, " is =", x)
    

The Crypto  BTC  is = 0
The Crypto  LTC  is = 1
The Crypto  BNB  is = 2
The Crypto  ETH  is = 3
The Crypto  MKR  is = 4


In [16]:
file["Crypto"].unique()

array([0, 3, 2, 1, 4], dtype=int64)

In [17]:
file.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Crypto', 'Today_USD',
       'Tomorrow_price(USD)'],
      dtype='object')

In [18]:
file.drop(["Date","Today_USD"], inplace =True, axis =True)

# Scaling

In [19]:
file.head()

Open        High         Low       Close  Crypto  Tomorrow_price(USD)
0  361.894989  363.066986  344.950989  352.218994       0           352.384003
1  352.204987  352.384003  346.364990  346.364990       0           361.356995
2  344.339996  361.356995  338.763000  350.506012       0           352.983002
3  350.833008  352.983002  349.290985  352.541992       0           352.381012
4  352.381012  352.381012  346.588013  347.376007       0           353.316010

In [20]:
from sklearn.model_selection import train_test_split

X = file.iloc[:,:-1]
Y = file.iloc[:,-1]

In [21]:
#X.to_csv("Crypto_input.csv")

from sklearn.preprocessing import MinMaxScaler
#sc = MinMaxScaler()
scaler_x = MinMaxScaler()
scaler_y = MinMaxScaler()

scaler_x.fit(X)
X_sc = scaler_x.transform(X)
Y_sc = scaler_y.fit(file[["Tomorrow_price(USD)"]])
Y_sc =scaler_y.fit_transform(file[["Tomorrow_price(USD)"]])
X_sc,Y_sc


In [22]:
#X,Y

In [23]:
#scaler_x.inverse_transform(X_sc)
#scaler_y.inverse_transform(Y_sc)


In [24]:
X_train,X_test, Y_train, Y_test = train_test_split( X, Y,test_size = 0.2, random_state = 42)

# machine learning algarithams comparitions

In [25]:
X_train

Open         High          Low        Close  Crypto
1937  6245.624512  6250.467285  5920.085938  5922.042969       0
5628    14.397900    14.422300    13.934500    13.991900       2
5381    98.861572   102.160332    98.499702   100.617645       1
1346  6294.229980  6473.500000  6276.410156  6334.729980       0
4127    61.098598    61.729698    59.740002    60.208099       1
...           ...          ...          ...          ...     ...
6885   541.403809   545.151978   525.121643   526.246521       2
6342    16.038355    16.252193    15.980892    16.001226       2
6541    41.775536    42.192703    40.592529    42.165955       2
860   1183.250000  1194.900024  1172.650024  1193.910034       0
4101    67.667900    68.118797    58.437698    58.437698       1

[8103 rows x 5 columns]

In [26]:
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.linear_model import SGDRegressor
from sklearn.linear_model import Lasso
from xgboost import XGBRegressor
#from xgboost import XGBRegressor
from sklearn.linear_model import Ridge 
from sklearn.ensemble import RandomForestRegressor 
lr = LinearRegression()
svr =SVR()
sgdr = SGDRegressor()
ls = Lasso()
xgbr = XGBRegressor()
r = Ridge()
rfr = RandomForestRegressor()

alg = [lr, svr, sgdr, ls, xgbr, r,rfr]

In [27]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score

from math import sqrt

#rms = sqrt(mean_squared_error(y_actual, y_predicted))

In [28]:
for  x in alg:
    x.fit(X_train, Y_train)
    predict = x.predict(X_test)
    mse = mean_squared_error(Y_test, predict)
    rms = np.sqrt(mse)
    mae = mean_absolute_error(Y_test, predict)
    r2 = r2_score(Y_test, predict)

    print(x,"\n mse = ",mse,";  rms = ",rms," mae = ", mae, "R2 = ",r2)
    print()


LinearRegression() 
 mse =  80441.4622937469 ;  rms =  283.62204126926895  mae =  72.16039204886188 R2 =  0.9991410881036368

SVR() 
 mse =  96607471.97655879 ;  rms =  9828.910009586963  mae =  3068.898881189831 R2 =  -0.031524099540118256

SGDRegressor() 
 mse =  1.3450059397057405e+32 ;  rms =  1.1597439112604732e+16  mae =  3798913925743709.5 R2 =  -1.436127053575856e+24

Lasso() 
 mse =  102193.8260130315 ;  rms =  319.6776908278579  mae =  79.94725695229333 R2 =  0.9989088277314385

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
             gamma=0, gpu_id=-1, importance_type=None,
             interaction_constraints='', learning_rate=0.300000012,
             max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
             monotone_constraints='()', n_estimators=100, n_jobs=4,
             num_parallel_tree=1, predictor='auto', random_state=0, reg_alpha=0,
          

# Prediction Testiong

In [29]:

lr.fit(X_train, Y_train)
predictlr = lr.predict(X_test)
mse = mean_squared_error(Y_test, predictlr)
rms = np.sqrt(mse)
mae = mean_absolute_error(Y_test, predictlr)
r2 = r2_score(Y_test, predictlr)

print(x,"\n mse = ",mse,";  rms = ",rms," mse = ", mae, "R2 = ",r2)
print()
predictlr

RandomForestRegressor() 
 mse =  80441.4622937469 ;  rms =  283.62204126926895  mse =  72.16039204886188 R2 =  0.9991410881036368



array([ 444.48031001,  453.21532685, 8146.43401366, ...,  579.14384841,
        368.33869666,  113.43471004])

actual value form testing dataset

In [30]:
Y_test[:10]

8859     423.890991
532      450.298004
1155    8509.110352
4600      62.165672
6073      15.824426
2030    9309.754883
4267      49.183182
1441    4951.609863
1373    6535.410156
7155     736.976990
Name: Tomorrow_price(USD), dtype: float64

predicted value

In [31]:
predictlr[:10].T

array([ 444.48031001,  453.21532685, 8146.43401366,   65.10238665,
         21.46467044, 9333.52750202,   51.27906194, 5103.6393788 ,
       6485.91426354,  756.06447439])

In [32]:
import joblib
joblib.dump(lr,"High_lr.pkl")

['High_lr.pkl']